services:
  apiservice:
    build:
      context: ..
      dockerfile: ./docker/apiservice.Dockerfile
    networks:
      - diststorage
    ports:
      - :7001:80/tcp
    command: ["/apiservice", "--inventory-port", "3609", "--chunks-num", "6"]

  storageservice:
    build:
      context: ..
      dockerfile: ./docker/storageservice.Dockerfile
    networks:
      - diststorage
    command: ["/storageservice", "--storage-location", "/opt/diststorage/storage", "--inventory-host", "apiservice:3609"]
    scale: 6

networks:
  diststorage: {}
