services:
  apiservice:
    build:
      context: ..
      dockerfile: ./docker/apiservice.Dockerfile
    networks:
      - diststorage
    ports:
      - :7001:80/tcp
    volumes:
      - diststorage-apiservice:/opt/diststorage/apiservice
    command: ["/apiservice", "--inventory-port", "3609", "--chunks-num", "6"]

  storageservice:
    build:
      context: ..
      dockerfile: ./docker/storageservice.Dockerfile
    networks:
      - diststorage
    volumes:
      - diststorage-storage:/opt/diststorage/storage
    command: ["/storageservice", "--storage-location", "/opt/diststorage/storage", "--inventory-host", "apiservice:3609"]
    scale: 6

volumes:
  diststorage-apiservice: {
    name: "diststorage-apiservice"
  }
  diststorage-storage: {
    name: "diststorage-storageservice"
  }

networks:
  diststorage: {}
