// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: storageinventory.proto

package storageinventory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageInventory_UpdateStorageInfo_FullMethodName = "/storage.StorageInventory/UpdateStorageInfo"
)

// StorageInventoryClient is the client API for StorageInventory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageInventoryClient interface {
	UpdateStorageInfo(ctx context.Context, in *StorageInfo, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type storageInventoryClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageInventoryClient(cc grpc.ClientConnInterface) StorageInventoryClient {
	return &storageInventoryClient{cc}
}

func (c *storageInventoryClient) UpdateStorageInfo(ctx context.Context, in *StorageInfo, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StorageInventory_UpdateStorageInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageInventoryServer is the server API for StorageInventory service.
// All implementations must embed UnimplementedStorageInventoryServer
// for forward compatibility.
type StorageInventoryServer interface {
	UpdateStorageInfo(context.Context, *StorageInfo) (*emptypb.Empty, error)
	mustEmbedUnimplementedStorageInventoryServer()
}

// UnimplementedStorageInventoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageInventoryServer struct{}

func (UnimplementedStorageInventoryServer) UpdateStorageInfo(context.Context, *StorageInfo) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStorageInfo not implemented")
}
func (UnimplementedStorageInventoryServer) mustEmbedUnimplementedStorageInventoryServer() {}
func (UnimplementedStorageInventoryServer) testEmbeddedByValue()                          {}

// UnsafeStorageInventoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageInventoryServer will
// result in compilation errors.
type UnsafeStorageInventoryServer interface {
	mustEmbedUnimplementedStorageInventoryServer()
}

func RegisterStorageInventoryServer(s grpc.ServiceRegistrar, srv StorageInventoryServer) {
	// If the following call pancis, it indicates UnimplementedStorageInventoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageInventory_ServiceDesc, srv)
}

func _StorageInventory_UpdateStorageInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorageInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageInventoryServer).UpdateStorageInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageInventory_UpdateStorageInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageInventoryServer).UpdateStorageInfo(ctx, req.(*StorageInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageInventory_ServiceDesc is the grpc.ServiceDesc for StorageInventory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageInventory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.StorageInventory",
	HandlerType: (*StorageInventoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateStorageInfo",
			Handler:    _StorageInventory_UpdateStorageInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storageinventory.proto",
}
